### PR TITLE
Add MMS

### PR DESCRIPTION
**Pull request by fxpy**
Add MMS validator for Evmos, Gravity-Bridge, Konstellation, Umee

### CODE REVIEW

**Comment by franono** [comment]
Hey, @tombeynon @fxpy this PR merge duplicated our validator on Gravity Bridge (Simply Staking), and changed the recompounding settings on the duplicate. Would it be possible to fix this please? 

It's resulting in our delegators getting misled on this chain.

**Comment by tombeynon** [comment]
@franono to confirm, it should be once per 24 hours at 20:00 ? I'll remove @fxpy 's addition.

Networks.json will be changing imminently, should help with this kind of thing.

**Comment by tombeynon** [comment]
Removing in #379

**Comment by fxpy** [comment]
My fault, due to mistake there was duplicate to another Gravity-Bridge validator. Will double-check next time, sorry for this

**Comment by tombeynon** [comment]
No problem, easily done with this file. I'm just preparing https://github.com/eco-stake/validator-registry to extract all this config.

**Pull request merged**
