### PR TITLE
Added Simply Staking Validators + New Networks

### PR DESCRIPTION
**Pull request by jacquesvcritien**
* Added Simply Staking Validators
* Added Bitsong, Persistence and Agoric Networks
* Added networks with no support for Authz: ImpactHub, Kichain and Sommelier

### CODE REVIEW

**Comment by tombeynon** [comment]
Awesome, especially the new networks! Will merge this later once I've had a chance to test

**Comment by tombeynon** [comment]
Awesome, especially the new networks! Will merge this later once I've had a chance to test

**Comment by tombeynon** [comment]
Few of the networks here will require #91, I'll merge with that as it's almost ready

**Comment by franono** [comment]
Do you have an ETA @tombeynon when that will be merged by any chance? So that we align marketing this awesome restake UI of your's :)

**Comment by tombeynon** [comment]
@franono will be in a few hours 🚀

**Pull request merged**
