### PR TITLE
Add Crescent

### PR DESCRIPTION
**Pull request by tombeynon**

### CODE REVIEW

**Comment by clemensgg** [comment]
will this be merged soon? Already PR'd our crescent config to the validator-registry ;)

**Comment by tombeynon** [comment]
Haha sorry, got caught up on other things. LFG 🚀

**Comment by tombeynon** [comment]
@clemensgg was crescent in your PR? Seems to still just be Polkachu

**Comment by tombeynon** [comment]
Live tho https://restake.app/crescent

**Pull request merged**
