### PR TITLE
Gas usage optimization

### PR DESCRIPTION
**Pull request by mr-kenikh**
I would like to propose a change that might slightly optimize gas usage by reducing the number of messages in a transaction. It is not necessary to collect the rewards first and then make the delegation, it is just enough to delegate.

Pros: reduced costs for validators who serve a large number of delegators.
Cons: the transaction becomes less informative. It may not be clear from which funds the delegation comes. Often explorers have an "auto claim rewards" field, which partially resolves this problem.

Examples:
1) [Get reward + delegate (current implementation)](https://explorer.yummy.capital/txs/33FEF1A65ADFCDE1D7F93F9D91B2E3FE95940600269E58BC2A8B9B763B57FBFC)
2) [Delegate only (current propose)](https://explorer.yummy.capital/txs/55757468E060F16BD1B1E27C0AD7BD20A7B713FFFE3F5D75A4AFB0E0B49393FB)

### CODE REVIEW

**Comment by mr-kenikh** [comment]
What do you mean by "for users without a balance"? We don't touch user's balance, because we pay fees.
Current propose is the same as current implementation, but the only difference is that the rewards are claimed automatically.

1) Firstly, we fetch total rewards here:
https://github.com/eco-stake/restake/blob/d5d0b468d1e17e090f32c7c135b928cc181d5045/scripts/base.mjs#L242

2) And then use this value here:
https://github.com/eco-stake/restake/blob/d5d0b468d1e17e090f32c7c135b928cc181d5045/scripts/base.mjs#L322

3) Thus, there is no way to touch user's balance. Moreover, user's balance will increase as you described in [this issue](https://github.com/eco-stake/restake/issues/399) (btw, that issue can't be resolved).

**Comment by tombeynon** [comment]
The result of this TX would mean the user had a non-zero balance, but if they had e.g 0.001 balance and 0.1 of rewards, I'm pretty sure the TX would fail with your change. 

Very happy to be proven wrong though. We _could_ still take advantage of this since we know the users balance beforehand and could only include the Withdraw if necessary.

**Comment by mr-kenikh** [comment]
https://explorer.yummy.capital/txs/31DEC0F17AF797793D016436A5096E1D58FE58F3DF8061B18D4D716167F3BE79

Target address: cro1rkvlrss04eay5mll79nclr3nc34rq9qnedc6k0
a) balance before: 1.00809988
b) restaked amount: 1.01416654
c) auto claim rewards: 1.01441617
d) balance after: 1.00834951

1) b > a, what was required for testing
2) с > b, as expected
3) a + (c - b) = d, as expected
4) transaction succeeded, as expected 😄

**Comment by tombeynon** [comment]
Wow.. I am very glad to be proven wrong. This is awesome and works great in my testing! I'm sure I tried this originally... 

I'm just preparing a second PR which will also remove all of the Withdraw grant functionality from the UI etc too. We can simplify quite a few things with this change. Will look to release later today.

FYI this saves approx another 25% of the total gas fee which is brilliant. Combined with #481 we should be in the region of 50% gas saved overall.

**Pull request merged**
