### PR TITLE
networks: add cheqd network

### PR DESCRIPTION
**Pull request by pwnfoo**
Cosmos registry info [here](https://github.com/cosmos/chain-registry/blob/master/cheqd/chain.json).

### CODE REVIEW

**Comment by pwnfoo** [comment]
Please wait until denoms are fixed until this is merged

**Comment by tombeynon** [comment]
@pwnfoo should be able to get denom work in later. What is cheqd denom factor out of interest?

**Comment by pwnfoo** [comment]
cheqd is `10^9` and uses `ncheq`

**Comment by pwnfoo** [comment]
@tombeynon Feel free to merge if the chain info looks good, I will work on a UI and launch it once the other PR is sorted 🚀 

Great project btw :)

**Comment by tombeynon** [comment]
Thanks again for this @pwnfoo ! Unfortunately won't work without the linked issue, but it's so close.. I'll get to this asap

**Comment by pwnfoo** [comment]
Hey @tombeynon, it wasn't working because of the typo in `decimal` set in cheqd, that's fixed.

**Comment by tombeynon** [comment]
Aghr stupid, thanks @pwnfoo ! I'm just finishing up another PR which will allow SuggestChain to work, and will then merge this and #89. Will be live before the weekend.

**Pull request merged**
