### PR TITLE
Refactoring RestClient

### PR DESCRIPTION
**Pull request by msteiner96**
Let's use CosmJS better here. Work in progress.

### CODE REVIEW

**Comment by tombeynon** [comment]
Thanks so much for this @msteiner96! This was my first project with React AND cosmjs so there are a lot of things that need this kind of improvement, and it's extremely valuable for me too to learn from you. Please keep anything like this coming 🔥

**Comment by msteiner96** [comment]
Yep no worries, gonna help you on that. Just need to go through everything, could take some time. But really like your project and I think it's worth the time ;)

**Comment by tombeynon** [comment]
I've spent quite a lot of time merging this today but have run into a number of problems.

1. Unsure if we can control pagination but this could be limiting
2. Rewards return an extremely high incorrect number
3. Attribute case changes, e.g. validator_address -> validatorAddress which just needs fixing
4. Delegations response is different key than in this code
5. Is the RPCClient the recommended way to do things? I found very little documentation. Would be nice to standardise with just an RPC endpoint but is this the optimal route?

There's a lot I really like in this PR so I'm keen to merge it, but rewards was the deal breaker so far. I have a branch with this merged into the release I'm working on, which I'll keep just in case, but will bring up to date with master once that's out.

**Comment by msteiner96** [comment]
Yes the pagination stuff is a problem here. We should probably let the app / user paginate instead of pulling everything.

We're working on the docs. But feel free to take a look in https://cosmwasm.github.io/CosmWasmJS/clients/reading/queries/.

I'll try to fix the other problem tommorow :)

**Comment by tombeynon** [comment]
Closing this for the time being but excited to pick this back up again at some point @msteiner96. Appreciate all your help

**Pull request closed without merging**
