### PR TITLE
get the full list of delegators

### PR DESCRIPTION
**Pull request by Galadrin**
The list of delegators is limited to 1000 in the script.
This patch allow to retrieve the full list of delegators by using pages.

The query can get a lower amount of delegators per request

N.B: it is a draft PR because not fully tested.

### CODE REVIEW

**Comment by tombeynon** [comment]
Ah excellent, this is top of my todo list right now. We need to take it a little further - if you have 1,000 delegations then we're gonna throw 1,000 API requests to get the grants at the same time, which does not go well. Will need to batch up the requests into groups of ~50-100 I think using this: https://github.com/eco-stake/restake/blob/master/scripts/autostake.mjs#L62

**Comment by tombeynon** [comment]
cc @imperator-co

**Comment by Galadrin** [comment]
> Ah excellent, this is top of my todo list right now. We need to take it a little further - if you have 1,000 delegations then we're gonna throw 1,000 API requests to get the grants at the same time, which does not go well. Will need to batch up the requests into groups of ~50-100 I think using this: https://github.com/eco-stake/restake/blob/master/scripts/autostake.mjs#L62

You cannot batch the REST requests to know if you are granted and if the rewards are suffisant.
This will burst the REST api endpoint who will reply with an error 429 (Too Many Requests)

But with more than 1000 delegators, you must have your own RPC/REST endpoints.

the Exec tx can be sent in batch ( list of messages )
this will create less stress on the chain and reduce the risk of sequence mismatch.

**Comment by tombeynon** [comment]
Thanks again for this @Galadrin , will be resolved in https://github.com/eco-stake/restake/pull/21.

Also added an issue about batched MsgExec, great idea #51

**Comment by tombeynon** [comment]
Thanks again for this @Galadrin , will be resolved in https://github.com/eco-stake/restake/pull/21.

Also added an issue about batched MsgExec, great idea #51

**Pull request closed without merging**
