### PR TITLE
Add note to tear down docker images

### PR DESCRIPTION
**Pull request by dylanschultzie**

### CODE REVIEW

**Comment by dylanschultzie** [comment]
@gh0stdotexe you might be interested in this as well as I believe you're also using docker?

**Comment by ericjohncarlson** [comment]
`05 00 01 * * /usr/bin/docker image prune -a -f`

I added another crontab entry for a monthly cleanup. I think this could be something to add.

**Comment by tombeynon** [comment]
Thanks for looking into this @dylanschultzie! It's not very clear but the `--rm` switch in all the `docker compose run...` commands is meant to handle this. It was added to the docs immediately so everyone who started using REStake early might not have included it in their cron/scheduler config. 

I think it's worth mentioning this in the README anyway, but might adjust the wording slightly or add to an FAQ. I'll leave this open and will pick it up ASAP.

**Comment by gh0stdotexe** [comment]
> @gh0stdotexe you might be interested in this as well as I believe you're also using docker?

Am currently using Docker but about to switch over to the NPM setup, thank you though, this does look useful!

**Pull request merged**
