### PR TITLE
Add BitCanna chain

### PR DESCRIPTION
**Pull request by RaulBernal**
On block 4490420 `authz` module will be activated. ;)

Please edit name, change `bitcanna-1` by `bitcanna` and wait next upgrade is passed.  🙏 
Aug 11th at 16.15.
Thanks

### CODE REVIEW

**Comment by tombeynon** [comment]
Thanks @RaulBernal ! Can you tell me - does the chain ID change in this update? Ultimately REStake is driven by the Chain Registry so we shouldn't need any updates to networks.json. Cosmos.directory will recognise that Authz has been enabled and REStake will update accordingly. 

Assuming all the info in Chain Registry is correct (code version doesn't matter in the context of REStake), then it should 'just work' (famous last words).

https://github.com/cosmos/chain-registry/blob/master/bitcanna/chain.json

**Comment by RaulBernal** [comment]
Awesome!
BTW the chain ID remains as `bitcanna-1`

**Comment by tombeynon** [comment]
Closing as Bitcanna update works fine and this info is sourced from Chain Registry

**Comment by RaulBernal** [comment]
Thanks

**Pull request closed without merging**
