### PR TITLE
command fix

### PR DESCRIPTION
**Pull request by CosmosElon**
change  "docker-compose"  for "docker compose"  in 'crontab -e' setup

(this is the only successful way for me)

### CODE REVIEW

**Comment by joshlopes** [comment]
I don't think this is correct thought, `docker` and `docker-compose` are different things

**Comment by CosmosElon** [comment]
At least here, crontab doesn't run the command if it has dash"-" in docker-compse.  So only "docker compose" worked for me.

**Comment by joshlopes** [comment]
You will have to tell me exactly what is the error, copy the whole command and try to run on your console. Grab all the output and paste it here so I can see what is happening.

**Comment by CosmosElon** [comment]
bash: docker-compose: command not found

**Comment by nullmames** [comment]
the issue is with the version of docker you are using. The new version has changed to a argument for `docker` as you say `docker compose`, the old version was a separate bin `docker-compose`. 

Best to note this diffrence in the documentation than just include one or the other. Something like, "Since vx.x.x the command `docker-compose` has been depricated and is now `docker compose`.

**Comment by CosmosElon** [comment]
> the issue is with the version of docker you are using. The new version has changed to a argument for `docker` as you say `docker compose`, the old version was a separate bin `docker-compose`.
> 
> Best to note this diffrence in the documentation than just include one or the other. Something like, "Since vx.x.x the command `docker-compose` has been depricated and is now `docker compose`.
> 
> If you were a subscriber to Game of Nodes, you would know this.
> 
> https://www.youtube.com/channel/UCWsyvi27z0i2bmOyBw1MAKA

Nice! I'm subscribed :)
Well then, that's what you explained. This notification will be good for anyone installing an updated version.

**Comment by tombeynon** [comment]
Thanks for the solving guys, perfect.

**Pull request merged**
