### PR TITLE
Updated documentation for systemd execution

### PR DESCRIPTION
**Pull request by HS-Joe**
Hey guys i wrote the installation guide for those who don't like docker
Feel free to adapt it!

### CODE REVIEW

**Comment by tombeynon** [comment]
You hero @HS-Joe , thank you for doing this! I might tweak for Node 17 as that's what I used to build it (should have pinned it long before now!), but otherwise it's perfect.

**Comment by HS-Joe** [comment]
Oh ok, it's working perfectly with 16 for what i've seen :)
Amazing work you are doing guys, congrats!!

**Comment by tombeynon** [comment]
@HS-Joe Ah good to know about 16. Could you split the README update into a separate branch so we don't pull your other updates in as well?

**Comment by HS-Joe** [comment]
OK will do in the next days! Also working on nginx configuration, i'll update the readme with this too (far from easy lol)

**Pull request closed without merging**
