### PR TITLE
Adding Source Protocol to networks.json

### PR DESCRIPTION
**Pull request by zenodeapp**
Hi!

Here's a request to add the Source protocol to the networks.json file. I made sure to only add the necessary values in order for autostaking _(or transactions in general)_ to work; which are the `gasPrice` and `gasModifier`.

Have a great day!

PS: I didn't see any other network with the `gasModifier` value set, but I presume it should work since some have the `autostake` object included.

---

https://sourceprotocol.io
https://restake.app/source

### CODE REVIEW

**Comment by zenodeapp** [comment]
One question:
Will we still be able to add "autostake" values in our local network files without it overwriting the `gasModifier` value, unless explicitly overwritten? Asking because I'm not sure how the final configuration gets merged together.

Is it a deep merge like this example with the use of spread operators?
`{...sourceNetwork, ...sourceNetworkLocal, "autostake": {...sourceNetwork.autostake, ...sourceNetworkLocal.autostake}`

**Comment by zenodeapp** [comment]
Hey, so I think a few more tests have to be run and the gas issues have to be sorted out before actually merging this.

Is it okay to keep this one open? Or you prefer to have this PR closed and reopened on a later time (if this even still becomes a necessity)?

**Comment by tombeynon** [comment]
@zenodeapp thanks for this! 

[Chain Registry](https://github.com/cosmos/chain-registry/blob/master/source/chain.json#L21C1-L21C1) suggests the 'low' gas price is 0.05usource - does using that avoid the need to set the gasModifier? Main reason being it gets expensive quickly if the modifier is set too high, and I haven't had to adjust this for any other chains so far.

**Comment by zenodeapp** [comment]
> @zenodeapp thanks for this!
> 
> [Chain Registry](https://github.com/cosmos/chain-registry/blob/master/source/chain.json#L21C1-L21C1) suggests the 'low' gas price is 0.05usource - does using that avoid the need to set the gasModifier? Main reason being it gets expensive quickly if the modifier is set too high, and I haven't had to adjust this for any other chains so far.

So sorry, just seeing this. Let me setup my validator to use such settings and I'll report back if it works fine or fails too often. (Even mine fails every once in 3-5 days, but are chain issues that probably need to be sorted out).

Bear with me! :)

**Comment by zenodeapp** [comment]
Wonder if I also should configure `gasPriceStep` then? If I set `gasPrice` to 0.05usource.

**Comment by zenodeapp** [comment]
I'll already change this PR to the 0.05usource, without modifier. I have it configured locally and set my restake frequency to 1hr. If it fails my healthchecker will alert me!

I'll keep ya posted :)!

**Comment by zenodeapp** [comment]
Okay, 1 day passed and so far I've had one fail happen out of ~24 successful ones.

image

This is normal (well not really normal, but expected).

It seems to cost 0.06 SOURCE per autostake now though versus 0.04 SOURCE, https://ping.pub/source/tx/CAC617AE1915994F2F5447D48E107E906D13852720F9C890AD1CCB8E3391058B (transaction before my change to 0.05usource) vs now: https://ping.pub/source/tx/16645FEE5DA03932CBA26232D0165313BA8C9A3CFDB9585EFF7F19593954058B

This is no biggy though! If it's better to leave `gasModifier` untouched then I believe this setting should be okay. I may need to play around with a higher value for `retry`, perhaps this will prevent it from failing too often (especially for people who have a less frequent restake).

I'll report back in a couple days! Have a good day man.

**Comment by zenodeapp** [comment]
I also changed `retries` to `10`. I saw in my logs that one of the autostake attempts was at its 7th attempt  (of 11 attempts) before it actually succeeded!

So the combi of `gasPrice` on 0.05usource and a higher `retries` value might be a better fix to prevent it from failing. And if it fails even after 11 attempts then...well, that would be more so an issue with the network rather than a problem we should fix.

Let me know what you think. If you agree, then I'll add the `retries` value also to the `networks.json` file (probably very uncommon, so therefore want to ask you first before I add it into this PR).

If you'd like to see the logs, tell me. At the moment I can't share it as I'm not behind a pc and this phone is giving me a hard time copying the logs in the Termux app :').

**Comment by zenodeapp** [comment]
> @tombeynon
> 
> I also changed `retries` to `10`. I saw in my logs that one of the autostake attempts was at its 7th attempt (of 11 attempts) before it actually succeeded!
> 
> So the combi of `gasPrice` on 0.05usource and a higher `retries` value might be a better fix to prevent it from failing. And if it fails even after 11 attempts then...well, that would be more so an issue with the network rather than a problem we should fix.
> 
> Let me know what you think. If you agree, then I'll add the `retries` value also to the `networks.json` file (probably very uncommon, so therefore want to ask you first before I add it into this PR).
> 
> If you'd like to see the logs, tell me. At the moment I can't share it as I'm not behind a pc and this phone is giving me a hard time copying the logs in the Termux app :').

Here's the log for reference:
[restake-source.log](https://github.com/eco-stake/restake/files/13454183/restake-source.log)

**Comment by zenodeapp** [comment]
Added `retries` 10 to the PR. Had no issues so far :)!

**Pull request merged**
